apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
    {{- include "buy.labels" . | nindent 4 }}
type: Opaque
data:
  buy_mongo_url: {{ .Values.buyMongoUrl | b64enc }}